server:
  port: 1987
  shutdown: GRACEFUL
  servlet:
    context-path: /kim-api
spring:
  application:
    name: kim
  profiles:
    active: sit
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      location: ${user.home}/multipartUpload
      max-file-size: 10MB
      max-request-size: 100MB
  lifecycle:
    timeout-per-shutdown-phase: 20s
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
management:
  server:
    port: 15000
#    servlet:
#      context-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
#  endpoints:
#    jmx:
#      exposure:
#        include: '*'
#    web:
#      base-path: /actuator
#      exposure:
#        include: '/actuator/*'
kim:
  kin:
    channel-no: '000'
    file-path: /data/file
    web-path: /kim-admin
jwt:
  base64EncodedSecretKey: kinkim
  expiration: 36000
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger
  try-host: http://localhost:${server.port}
