spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.222:3306/kinkim?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456
  jpa:
    show-sql: false
    generate-ddl: false
  data:
    redis:
      host: localhost
      password:
      port: 6379
      database: 0
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: a2lua2lt
    property:
      prefix: "im@kin.kim["
      suffix: "]"
    privateKeyFormat: pem
    publicKeyFormat: pem
    private-key-location: file:C:\\Users\\choky\\.ssh\\id_rsa_pkcs8
    public-key-location: file:C:\\Users\\choky\\.ssh\\id_rsa_pkcs8.pem
