spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kinkim?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: mail@whoimi.com[pP/XcBb1plHO10KZoJ/+eKbhqWpUJd1up7q7pRppp7FAZ7Hhgze3Q38N4ODhXgqBSbtPB1XQNddYgGC+dqWiUV6MoH/Gdiwqbx3+Qu0qHX/vTpwSfxAMl0raPkErCQQuTd5P7gwZPH394MUeK87Y96HyFL0rYy7lIr3TaylyokxOqUHrNUS83NuhA6Eenv9H3TCYURFrSOoyLuTKgEW19SIM+dch5iciE/hHv4Yi2EGDmng9RX2ZnghUllKD3aSinYZ/Vhe3v38Rc9lGbfFI1XUE173REFnJfXj/hH05pDSgxK3vsRBhQYFs1xcVIwhjmXrOawB2CwwSLsViNXeUnA==]
    password: mail@whoimi.com[SD9Swa4+2rIH4Xzx470BaCx/YMD/EkQrtpdQ8JlwBiDjmj4jEUy50abypNvFgSc3DvPIzSSI0292hcBSujYZ3Wg1l2xfbs4zzkITSZTduAgYR7J7TcRLffCcUpn2bXUf5j8Fw6z7zfwF0ndJNrh2pSrtmtTUSKz2ntF7Ed8B4MBjcnp++xzikCzlPdas5crLF0MC4ic0mX/olHAyzTMIx4e+USzmjGBlyvH/iuZQyHw02NQhRDjXaYZWM/UTvC4k3os40XciWLn286veRU9uO6vDV60s2O9cCqxWU1UQl6HEeDhOc6FhG2XuzY+toVKZD+MfUziV1Taw+Jm8+RYGyg==]
  data:
    redis:
      host: localhost
      password: im@kin.kim[NACfREF4LFIQFDM7MXotJilYF/b2gX+CkgvnPbRxRtqCiQ1UcZsqW2idQ2+fnxpnF6tGZlR+XYqvpMvRk7tms9B+Mv/M582EUk+gIdugS46sjzL/1q8RZ9fuVpNe6deWsggwqZwVXj1E7z/hKk4B0VAmY+32gIoRZrDxu/JSu52saCMjx1TIAvYPb4Ms8pO3xUo6M56ew9TAO0SKIHDR/4KpvrzrtsYKLUyyy31a0+WRNq/4n4CmqQXiDwuspMb5ap8V1g27nvhuPBytIhVOP7RdeV/kcSzMury9lKMbMrcBdGetC93s1mie7stn2uGx7ApMRRJo1ejjXK8ZbkQsrQ==]
      port: 6379
      database: 0
jasypt:
  encryptor:
    #    algorithm: PBEWITHHMACSHA512ANDAES_256
    #    password: a2lua2lt
    property:
      prefix: "mail@whoimi.com["
      suffix: "]"
    private-key-format: pem
    public-key-format: pem
    #    private-key-location: classpath:id_rsa_pkcs8
    #    public-key-location: classpath:id_rsa_pkcs8.pem
    private-key-location: file:/home/devops/.ssh/id_rsa_pkcs8
    public-key-location: file:/home/devops/.ssh/id_rsa_pkcs8.pem
